### ISSUE TITLE
Error during client generation `self referenced toctree found` due to service named `services`

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#825] opened 2021-03-24 17:30 UTC
The `appengine_admin` client has a service called `services` . Unfortunately, `services` is already an implicitly reserved keyword in `gapic-generator-python` templates here:
https://github.com/googleapis/gapic-generator-python/blob/master/gapic/templates/docs/%25name_%25version/services.rst.j2

As a result of having `service.rst` referencing another `service.rst`, I get a Sphinx error `self referenced toctree found` when generating the client.

```
sphinx.errors.SphinxWarning: /usr/local/google/home/partheniou/git/GOB/python-appengine-admin/docs/appengine_admin_v1/services.rst:self referenced toctree found. Ignored.
```

I'd like to propose to rename `docs/<api>/services` to `docs/<api>/services_` when there is a service called `services`. For example,

![image](https://user-images.githubusercontent.com/5184014/112356404-f6ea2f80-8ca4-11eb-8d85-3f56cb7d1201.png)

You can see that there is a service called `services` below:
![image](https://user-images.githubusercontent.com/5184014/112356597-213bed00-8ca5-11eb-87cd-674a168851b7.png)

**Comment by vam-google** [comment] 2022-01-19 23:30
@parthea Is this issues still relevant or do you already have a workaround for `appengine_admin`?

**Comment by parthea** [comment] 2022-01-20 22:41
We have a workaround but I'd like to propose that keep this issue open for tracking purposes as there is a bug in the generator. If we're already tracking this issue in another location then I'm happy to close it.

**Comment by parthea** [comment] 2022-03-18 11:21
I'm also seeing this issue in the generated client for cloud run [here](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/run/v2/run-v2-py/docs/run_v2/services.rst).

**Comment by vam-google** [comment] 2022-03-23 22:25
Lowering priority to P3 since there is a workaround. The issue is specific to naming conflict in one concrete API. To fix it properly we would need some sort of centralized name conflict resolution (since there are many other similar issues with name conflicts in gapic-generator, all being fixed by hacks, significantly complicating maintenance of it), but it is outside of scope of this bug.

**Comment by parthea** [comment] 2023-04-12 14:33
I have a prototype that works locally.  It requires some changes to synthtool (post processor) as well. I will open a PR next week.

**Closed** 2023-10-18 15:31 UTC
Labels: type: cleanup
