### ISSUE TITLE
Add retry and timeout params to pagers

### ISSUE THREAD

**Issue by gkevinzheng** [googleapis/gapic-generator-python#1877] opened 2023-11-28 20:44 UTC
If a client method returns a pager object, that pager object's `pages` method uses default retry and timeout parameters, rather than the ones specified in the client method parameters.

**Generated code:**

Client library call: https://github.com/googleapis/python-logging/blob/6591b53e3fcd67e156765f329700443647b70349/google/cloud/logging_v2/services/logging_service_v2/client.py#L871-L889

This is generated by https://github.com/googleapis/gapic-generator-python/blob/b64e7a3351804613aaf56d7a699390d8dbc70712/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/_client_macros.j2#L17

Pager: https://github.com/googleapis/python-logging/blob/6591b53e3fcd67e156765f329700443647b70349/google/cloud/logging_v2/services/logging_service_v2/pagers.py#L78-L89

This is generated by https://github.com/googleapis/gapic-generator-python/blob/b64e7a3351804613aaf56d7a699390d8dbc70712/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/pagers.py.j2#L24

In this code flow, the first rpc call in `client.py` is invoked with the user-specified retry and timeout. When execution is transferred to the returned `ListLogEntriesPager` object, however, it calls the `rpc` method with default retry and timeout, rather than the user-specified values. 

**Proposal:**

Add `retry=gapic_v1.method.DEFAULT` and `timeout=gapic_v1.method.DEFAULT` as parameters/instance variables to the pager template, then update the `self._method` call in https://github.com/googleapis/gapic-generator-python/blob/b64e7a3351804613aaf56d7a699390d8dbc70712/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/pagers.py.j2#L72 to use the specified retry and timeout.

**Comment by parthea** [comment] 2024-03-28 10:36
Duplicate of https://github.com/googleapis/gapic-generator-python/issues/1664

**Closed by parthea** 2024-03-28 10:36 UTC
Labels: type: bug, priority: p2
