### ISSUE TITLE
microgenerator: NameError: name 'operation' is not defined

### ISSUE THREAD

**Issue by dizcology** [googleapis/gapic-generator-python#336] opened 2020-03-05 23:26 UTC
After the update (https://github.com/googleapis/gapic-generator-python/pull/332), I am getting test failures `NameError: name 'operation' is not defined`.

The call looks like:

```
# in google/cloud/foo_v1/services/bar_service/client.py

# Wrap the response in an operation future.
>       response = operation.from_gapic(
...
```

(where it should be ga_operation)

**Comment by dizcology** [comment] 2020-03-05 23:27
@software-dov @busunkim96

**Comment by arithmetic1728** [comment] 2020-07-14 18:48
@software-dov any update?

**Comment by arithmetic1728** [comment] 2020-07-30 20:13
@dizcology Possibly `from google.api_core import operation` was missing from the generated code for that version. There has been a lot of changes lately in the generator, and it seems the problem is already fixed by looking at the generated clients. Please try the latest version again and reopen if you still see this issue. Thanks!

**Closed by arithmetic1728** 2020-07-30 20:13 UTC
Labels: generator, priority: p2, type: bug

**Comment by dizcology** [comment] 2020-10-19 20:47
Thank you - the issue has been fixed in my use case with the latest generator.
