### ISSUE TITLE
The result of publisher.list_topic_subscriptions() should be iterable

### ISSUE THREAD

**Issue by plamut** [googleapis/gapic-generator-python#537] opened 2020-07-17 06:20 UTC
(Spinning off from #530)

The result of `publisher.list_topic_subscriptions()` is not iterable. Unlike some other `list_*()` methods it directly returns `ListTopicSubscriptionsResponse` instead of something like `ListTopicSubscriptionsPager`. Developers thus need to iterate over `response.subscriptions`, which is somewhat less elegant and inconsistent with how results of the other `list_*()` methods can be handled.

**Comment by software-dov** [comment] 2020-07-17 17:45
Unable to reproduce with most current generator: list_topic_subscriptions is properly paginated in the generated surface. Duplicate of #516 ; closing as fixed.

**Closed by software-dov** 2020-07-17 17:45 UTC
Labels: type: feature request
