### ISSUE TITLE
Adding a new proto field breaks existing API clients

### ISSUE THREAD

**Issue by ikuleshov** [googleapis/gapic-generator-python#831] opened 2021-03-30 07:50 UTC
If a new field is added to an API service proto, all clients using outdated proto definitions receive the following error:

```
google.api_core.exceptions.InternalServerError: 500 Exception deserializing response!
```

Although it is never a good idea to modify an existing API proto (our team added a new minor field to the Alpha version of the API), this behavior is inconsistent with other platforms. API clients for Java, PHP, Node.js do not fail with a deserialization error, but simply ignore the new field and carry on.

**Comment by software-dov** [comment] 2021-03-30 16:40
This is definitely not correct behavior. Can you please provide environment and setup details, and possibly a stacktrace? There should be tests for this behavior in proto-plus, but depending on where the issue is really encountered those tests could be bypassing the problem.

**Comment by software-dov** [comment] 2021-04-12 20:40
Unable to recreate; closing for now.

**Closed by software-dov** 2021-04-12 20:40 UTC
Labels: :rotating_light:, priority: p1, type: bug
