### ISSUE TITLE
retry and timeout config not passed to next_page calls in Pagers

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/gapic-generator-python#1974] opened 2024-03-12 23:37 UTC
the gapic generator creates pager classes to make paging calls more friendly (example: Firestore's [ListDocumentsPager](https://github.com/googleapis/python-firestore/blob/f10b503b0dc2b23e43495e3f0417ae2630c13d82/google/cloud/firestore_v1/services/firestore/pagers.py#L32))

Currently, any retry or timeout configuration is only used for the initial call. Each subsequent page will use the api defaults for these values

Instead, we should use the same retry and timeout options for each call in the Pager. Or, alternatively, provide different `next_page_timeout` and `next_page_retry` if we want to treat them separately. But I don't think that is necessary

**Comment by parthea** [comment] 2024-03-28 10:36
Duplicate of https://github.com/googleapis/gapic-generator-python/issues/1664

**Closed by parthea** 2024-03-28 10:36 UTC
